### ISSUE TITLE
./somd/potentials/src/nep.cpp:1233:31: fatal error: NEP_CPU/src/nep.cpp: No such file or directory

### ISSUE THREAD

**Issue by starsparkling** [initqp/somd#8]
When installing somd, I encountered an error after running 'Python setup. py install' as follows:

g++ -pthread -B /data/home/wuxingxing/anaconda3/envs/gpumd/compiler_compat -shared -Wl,-rpath,/data/home/wuxingxing/anaconda3/envs/gpumd/lib -Wl,-rpath-link,/data/home/wuxingxing/anaconda3/envs/gpumd/lib -L/data/home/wuxingxing/anaconda3/envs/gpumd/lib -Wl,-rpath,/data/home/wuxingxing/anaconda3/envs/gpumd/lib -Wl,-rpath-link,/data/home/wuxingxing/anaconda3/envs/gpumd/lib -L/data/home/wuxingxing/anaconda3/envs/gpumd/lib build/temp.linux-x86_64-cpython-310/./somd/core/src/lib.o build/temp.linux-x86_64-cpython-310/./somd/core/src/math_utils.o -o build/lib.linux-x86_64-cpython-310/somd/core/_lib.cpython-310-x86_64-linux-gnu.so -fopenmp
building 'somd.potentials._nepwrapper' extension
creating build/temp.linux-x86_64-cpython-310/somd/potentials
creating build/temp.linux-x86_64-cpython-310/somd/potentials/src
gcc -pthread -B /data/home/wuxingxing/anaconda3/envs/gpumd/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /data/home/wuxingxing/anaconda3/envs/gpumd/include -fPIC -O2 -isystem /data/home/wuxingxing/anaconda3/envs/gpumd/include -fPIC -I./somd/potentials/src -I/data/home/wuxingxing/anaconda3/envs/gpumd/include/python3.10 -c ./somd/potentials/src/nep.cpp -o build/temp.linux-x86_64-cpython-310/./somd/potentials/src/nep.o -std=c++11 -Wall -fopenmp -O4 -march=native
./somd/potentials/src/nep.cpp:1233:31: fatal error: NEP_CPU/src/nep.cpp: No such file or directory
 #include "NEP_CPU/src/nep.cpp"
                               ^
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

I checked 'somd/notes/src/NEP_CPU‘ found that this directory is empty. May I know how to install it?

The code used here is https://github.com/initqp/somd Master branch

**Comment by initqp** [comment]
Dear WuXing,

Thank you for your interest in SOMD. I believe your error is caused by forgetting to invoke the `git submodule update --init` command. You should follow the installation process introduced in the `README.md` file, which is:

```bash
git clone https://www.github.com/initqp/somd
cd somd
git submodule update --init
python setup.py install
```

Once you have invoked the `git submodule update --init` command, files belonging to the `NEP_CPU` submodule will be downloaded. Then you can proceed by invoking `python setup.py install`.

Regards
